/**
 * Canonical internal authorization contract.
 *
 * Every entry point (HTTP, MCP proxy, future SDK) normalizes into this
 * structure before reaching the policy engine. The policy engine must never
 * import transport-specific types.
 */

export interface Principal {
  /** JWT `sub` claim — identifies the human user. */
  readonly sub: string;
  /** Value of the configured `agent_id_claim` — identifies the AI agent. */
  readonly agentId: string;
}

export interface AuthorizationContext {
  readonly sessionId?: string;
}

export interface AuthorizationRequest {
  /** UUID generated by Limekey at normalization time. */
  readonly requestId: string;
  /** ISO 8601 timestamp generated at normalization time. */
  readonly timestamp: string;

  readonly principal: Principal;

  readonly tool: string;
  readonly arguments: Record<string, unknown>;

  readonly context: AuthorizationContext;
}
